authors:
- Ansible
dependencies: {}
description: Bulk test collection tnsbabf21.tc88042189 (based on ansible.utils)
license:
- GPL-2.0-or-later
name: tc88042189
namespace: tnsbabf21
readme: README.md
repository: https://github.com/test/tnsbabf21.tc88042189
tags:
- networking
version: 6.0.2
